package iut.sae.graphmap.graph;

import iut.sae.graphmap.CompareDialog;
import iut.sae.graphmap.DistanceDialog;
import iut.sae.graphmap.FileSelectionDialog;
import iut.sae.graphmap.ListDialog;
import iut.sae.graphmap.models.Edge;
import iut.sae.graphmap.models.Node;
import iut.sae.graphmap.models.Path;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.MultiGraph;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.view.util.InteractiveElement;

/**
 * Represents the main window of the Program
 * @author Jonathan MONTMAIN, Rudy BOULLIER
 */
public class GraphVisualisationWindow extends javax.swing.JFrame {
    
    /**
     * Represents the shown graph
     */
    private Graph graph;
    
    /**
     * Represents the panel that shows the graph
     */
    private Component viewComponent;
    
    /**
     * Represents the selected node
     */
    private Node selectedNode;

    /**
     * Creates new form GraphVisualisationWindow
     */
    public GraphVisualisationWindow() {
        initComponents();
    }
    
    /**
     * Shows the window and open the FileSelectionDialog
     * @param b Visibility
     */
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if (b) openFileSelectionDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightPanel = new javax.swing.JPanel();
        nodeTitle = new javax.swing.JLabel();
        distancePanel = new javax.swing.JPanel();
        distanceOptionsPanel = new javax.swing.JPanel();
        maxDistanceLabel = new javax.swing.JLabel();
        maxDistanceSpinner = new javax.swing.JSpinner();
        visualizeButton = new javax.swing.JButton();
        comparePanel = new javax.swing.JPanel();
        firstCityComboBox = new javax.swing.JComboBox<>();
        secondCityComboBox = new javax.swing.JComboBox<>();
        firstCityLabel = new javax.swing.JLabel();
        secondCityLabel = new javax.swing.JLabel();
        compareButton = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        nodesInformationsLabel = new javax.swing.JLabel();
        edgesInformationsLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openFileMenuItem = new javax.swing.JMenuItem();
        separator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        displayMenu = new javax.swing.JMenu();
        displayNodesTitlesCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        displayDistancesCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        displayEdgesCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        showListDialog = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        displayNodesMenu = new javax.swing.JMenu();
        displayCitiesCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        displayLeisuresCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        displayRestaurantsCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        displayEdgesMenu = new javax.swing.JMenu();
        displayNationalRoadsCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        displayDepartementalRoadsCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        displayHighwaysCheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GraphMap");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        rightPanel.setMinimumSize(new java.awt.Dimension(300, 300));
        rightPanel.setPreferredSize(new java.awt.Dimension(300, 274));

        nodeTitle.setText("Aucun noeud sélectionné");

        distancePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Plus court chemin"));

        distanceOptionsPanel.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        maxDistanceLabel.setText("Distance maximale");
        distanceOptionsPanel.add(maxDistanceLabel);

        maxDistanceSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        distanceOptionsPanel.add(maxDistanceSpinner);

        visualizeButton.setText("Visualiser");
        visualizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout distancePanelLayout = new javax.swing.GroupLayout(distancePanel);
        distancePanel.setLayout(distancePanelLayout);
        distancePanelLayout.setHorizontalGroup(
            distancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, distancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(distancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(distanceOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(distancePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(visualizeButton)))
                .addContainerGap())
        );
        distancePanelLayout.setVerticalGroup(
            distancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distancePanelLayout.createSequentialGroup()
                .addComponent(distanceOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visualizeButton)
                .addContainerGap())
        );

        comparePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Comparaison"));

        firstCityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aucun" }));

        secondCityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aucun" }));

        firstCityLabel.setText("Ville 1");

        secondCityLabel.setText("Ville 2");

        compareButton.setText("Comparer");
        compareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comparePanelLayout = new javax.swing.GroupLayout(comparePanel);
        comparePanel.setLayout(comparePanelLayout);
        comparePanelLayout.setHorizontalGroup(
            comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comparePanelLayout.createSequentialGroup()
                        .addComponent(firstCityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(firstCityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comparePanelLayout.createSequentialGroup()
                        .addComponent(secondCityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(secondCityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comparePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(compareButton)))
                .addContainerGap())
        );
        comparePanelLayout.setVerticalGroup(
            comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comparePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstCityComboBox)
                    .addComponent(firstCityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(secondCityComboBox)
                    .addComponent(secondCityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(compareButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distancePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(nodeTitle)
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addComponent(comparePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nodeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(distancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comparePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setGroupEnabled(rightPanel, false);

        getContentPane().add(rightPanel, java.awt.BorderLayout.LINE_END);

        nodesInformationsLabel.setText("0 villes, 0 loisirs, 0 restaurants");

        edgesInformationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        edgesInformationsLabel.setText("0 nationales, 0 départementales, 0 autoroutes");

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nodesInformationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(edgesInformationsLabel)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodesInformationsLabel)
                    .addComponent(edgesInformationsLabel))
                .addContainerGap())
        );

        getContentPane().add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        fileMenu.setText("Fichier");

        openFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openFileMenuItem.setText("Ouvrir...");
        openFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openFileMenuItem);
        fileMenu.add(separator1);

        exitMenuItem.setText("Quitter");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        displayMenu.setText("Affichage");
        displayMenu.setToolTipText("");
        displayMenu.setEnabled(false);

        displayNodesTitlesCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        displayNodesTitlesCheckBoxMenuItem.setSelected(true);
        displayNodesTitlesCheckBoxMenuItem.setText("Afficher les titres des noeuds");
        displayNodesTitlesCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayNodesTitlesCheckBoxMenuItemActionPerformed(evt);
            }
        });
        displayMenu.add(displayNodesTitlesCheckBoxMenuItem);

        displayDistancesCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        displayDistancesCheckBoxMenuItem.setSelected(true);
        displayDistancesCheckBoxMenuItem.setText("Afficher les distances");
        displayDistancesCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDistancesCheckBoxMenuItemActionPerformed(evt);
            }
        });
        displayMenu.add(displayDistancesCheckBoxMenuItem);

        displayEdgesCheckBoxMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        displayEdgesCheckBoxMenuItem.setSelected(true);
        displayEdgesCheckBoxMenuItem.setText("Afficher les liaisons");
        displayEdgesCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayEdgesCheckBoxMenuItemActionPerformed(evt);
            }
        });
        displayMenu.add(displayEdgesCheckBoxMenuItem);
        displayMenu.add(jSeparator1);

        showListDialog.setText("Voir l'ensemble des noeuds et liaisons...");
        showListDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListDialogActionPerformed(evt);
            }
        });
        displayMenu.add(showListDialog);
        displayMenu.add(jSeparator2);

        displayNodesMenu.setText("Afficher les noeuds par type");

        displayCitiesCheckBoxMenuItem.setSelected(true);
        displayCitiesCheckBoxMenuItem.setText("Villes");
        displayCitiesCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCitiesCheckBoxMenuItemActionPerformed(evt);
            }
        });
        displayNodesMenu.add(displayCitiesCheckBoxMenuItem);

        displayLeisuresCheckBoxMenuItem.setSelected(true);
        displayLeisuresCheckBoxMenuItem.setText("Loisirs");
        displayLeisuresCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayLeisuresCheckBoxMenuItemActionPerformed(evt);
            }
        });
        displayNodesMenu.add(displayLeisuresCheckBoxMenuItem);

        displayRestaurantsCheckBoxMenuItem.setSelected(true);
        displayRestaurantsCheckBoxMenuItem.setText("Restaurants");
        displayRestaurantsCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayRestaurantsCheckBoxMenuItemActionPerformed(evt);
            }
        });
        displayNodesMenu.add(displayRestaurantsCheckBoxMenuItem);

        displayMenu.add(displayNodesMenu);

        displayEdgesMenu.setText("Afficher les liaisons par type");

        displayNationalRoadsCheckBoxMenuItem.setSelected(true);
        displayNationalRoadsCheckBoxMenuItem.setText("Nationales");
        displayNationalRoadsCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayNationalRoadsCheckBoxMenuItemActionPerformed(evt);
            }
        });
        displayEdgesMenu.add(displayNationalRoadsCheckBoxMenuItem);

        displayDepartementalRoadsCheckBoxMenuItem.setSelected(true);
        displayDepartementalRoadsCheckBoxMenuItem.setText("Départementales");
        displayDepartementalRoadsCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDepartementalRoadsCheckBoxMenuItemActionPerformed(evt);
            }
        });
        displayEdgesMenu.add(displayDepartementalRoadsCheckBoxMenuItem);

        displayHighwaysCheckBoxMenuItem.setSelected(true);
        displayHighwaysCheckBoxMenuItem.setText("Autoroutes");
        displayHighwaysCheckBoxMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayHighwaysCheckBoxMenuItemActionPerformed(evt);
            }
        });
        displayEdgesMenu.add(displayHighwaysCheckBoxMenuItem);

        displayMenu.add(displayEdgesMenu);

        menuBar.add(displayMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Enables a container as well as its children
     * @param parent Parent container
     * @param b Enabled state
     */
    private void setGroupEnabled(Container parent, boolean b) {
        parent.setEnabled(b);
        for (Component component : parent.getComponents()) {
            component.setEnabled(b);
            if (component instanceof Container) {
                setGroupEnabled((Container) component, b);
            }
        }
    }
    
    /**
     * Shows the FileSelectionDialog
     */
    private void openFileSelectionDialog() {
        File file = FileSelectionDialog.showDialog(this, graph != null);
        
        if (file != null) {
            graph = new MultiGraph(file.getName());
            graph.setAttribute("ui.quality");
            graph.setAttribute("ui.antialias");
            graph.setAttribute("ui.stylesheet", GraphStyles.getFullStyles());
            try {
                GraphParser.parse(file, graph);
            } catch(IOException ex) {
                JOptionPane.showMessageDialog(this, "Le fichier: \"" + file.getAbsolutePath() + "\" n'a pas pu être lu !", "Erreur lors de l'ouverture du fichier", JOptionPane.ERROR_MESSAGE);
            }
            Viewer viewer = new SwingViewer(graph, SwingViewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
            viewer.enableAutoLayout();
            View view = viewer.addDefaultView(false);
            view.enableMouseOptions();
            ((Component) view).addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent evt) {
                    int x = evt.getX();
                    int y = evt.getY();
                    org.graphstream.graph.Node node = (org.graphstream.graph.Node) view.findGraphicElementAt(EnumSet.of(InteractiveElement.NODE), x, y);
                    if (node != null) {
                        selectedNode = Node.findNode(node.toString());
                        nodeTitle.setText((selectedNode != null) ? "Selection: " + selectedNode.getName() : "Aucun noeud sélectionné");
                        setGroupEnabled(distancePanel, selectedNode != null);
                    } else {
                        selectedNode = null;
                        nodeTitle.setText("Aucun noeud sélectionné");
                        setGroupEnabled(distancePanel, false);
                    }
                }
            });
            if (viewComponent != null) this.remove(viewComponent);
            viewComponent = (Component) view;
            this.add(viewComponent, BorderLayout.CENTER);
            setGroupEnabled(rightPanel, true);
            setGroupEnabled(displayMenu, true);
            setGroupEnabled(distancePanel, false);
            this.firstCityComboBox.setModel(new CityComboBoxModel(Node.getRegisteredNodes()));
            this.secondCityComboBox.setModel(new CityComboBoxModel(Node.getRegisteredNodes()));
            int cities = 0;
            int leisures = 0;
            int restaurants = 0;
            for (Node node : Node.getRegisteredNodes()) {
                switch (node.getType()) {
                    case V:
                        cities++;
                        break;
                    case L:
                        leisures++;
                        break;
                    case R:
                        restaurants++;
                        break;
                }
            }
            this.nodesInformationsLabel.setText(cities + " villes, " + leisures + " loisirs, " + restaurants + " restaurants");
            int highways = 0;
            int nationalRoads = 0;
            int departementalRoads = 0;
            for (Edge edge : Edge.getRegisteredEdges()) {
                switch (edge.getType()) {
                    case N:
                        nationalRoads++;
                        break;
                    case D:
                        departementalRoads++;
                        break;
                    case A:
                        highways++;
                        break;
                }
            }
            this.edgesInformationsLabel.setText(nationalRoads + " nationales, " + departementalRoads + " départementales, " + highways + " autoroutes");
            this.validate();
            this.repaint();
            updateVisibility();
        }
    }
    
    /**
     * Handles click on "Open file"
     * @param evt Action event
     */
    private void openFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileMenuItemActionPerformed
        openFileSelectionDialog();
    }//GEN-LAST:event_openFileMenuItemActionPerformed

    /**
     * Handles click on "Exit"
     * @param evt Action event
     */
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * Handles click on "Visualize"
     * @param evt Action event
     */
    private void visualizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizeButtonActionPerformed
        List<Path> paths = new ArrayList<>();
        for (Node node : Node.getRegisteredNodes()) {
            if (node == selectedNode) continue;
            paths.add(Path.findShortestPath(this.graph, selectedNode, node));
        }
        DistanceDialog.showDialog(this, selectedNode, paths, (int) maxDistanceSpinner.getValue());
    }//GEN-LAST:event_visualizeButtonActionPerformed

    /**
     * Handles click on "Display nodes titles"
     * @param evt Action event
     */
    private void displayNodesTitlesCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayNodesTitlesCheckBoxMenuItemActionPerformed
        graph.setAttribute("ui.stylesheet", GraphStyles.toggleNodesTitles(displayNodesTitlesCheckBoxMenuItem.isSelected()));
    }//GEN-LAST:event_displayNodesTitlesCheckBoxMenuItemActionPerformed

    /**
     * Handles click on "Compare"
     * @param evt Action event
     */
    private void compareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareButtonActionPerformed
        if (firstCityComboBox.getSelectedIndex() >= 0 && secondCityComboBox.getSelectedIndex() >= 0)
            CompareDialog.showDialog(this, Node.getRegisteredNodes().get(firstCityComboBox.getSelectedIndex()), Node.getRegisteredNodes().get(secondCityComboBox.getSelectedIndex()));
    }//GEN-LAST:event_compareButtonActionPerformed

    /**
     * Handles click on "Display cities"
     * @param evt Action event
     */
    private void displayCitiesCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCitiesCheckBoxMenuItemActionPerformed
        updateVisibility();
    }//GEN-LAST:event_displayCitiesCheckBoxMenuItemActionPerformed

    /**
     * Handles click on "Display leisures"
     * @param evt Action event
     */
    private void displayLeisuresCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayLeisuresCheckBoxMenuItemActionPerformed
        updateVisibility();
    }//GEN-LAST:event_displayLeisuresCheckBoxMenuItemActionPerformed

    /**
     * Handles click on "Display restaurants"
     * @param evt Action event
     */
    private void displayRestaurantsCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayRestaurantsCheckBoxMenuItemActionPerformed
        updateVisibility();
    }//GEN-LAST:event_displayRestaurantsCheckBoxMenuItemActionPerformed

    /**
     * Handles click on "Display national roads"
     * @param evt Action event
     */
    private void displayNationalRoadsCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayNationalRoadsCheckBoxMenuItemActionPerformed
        updateVisibility();
    }//GEN-LAST:event_displayNationalRoadsCheckBoxMenuItemActionPerformed

    /**
     * Handles click on "Display departemental roads"
     * @param evt Action event
     */
    private void displayDepartementalRoadsCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDepartementalRoadsCheckBoxMenuItemActionPerformed
        updateVisibility();
    }//GEN-LAST:event_displayDepartementalRoadsCheckBoxMenuItemActionPerformed

    /**
     * Handles click on "Display highways"
     * @param evt Action event
     */
    private void displayHighwaysCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayHighwaysCheckBoxMenuItemActionPerformed
        updateVisibility();
    }//GEN-LAST:event_displayHighwaysCheckBoxMenuItemActionPerformed

    /**
     * Handles click on "Display distances"
     * @param evt Action event
     */
    private void displayDistancesCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDistancesCheckBoxMenuItemActionPerformed
        graph.setAttribute("ui.stylesheet", GraphStyles.toggleDistances(displayDistancesCheckBoxMenuItem.isSelected()));
    }//GEN-LAST:event_displayDistancesCheckBoxMenuItemActionPerformed

    /**
     * Handles click on "Display edges"
     * @param evt Action event
     */
    private void displayEdgesCheckBoxMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayEdgesCheckBoxMenuItemActionPerformed
        displayEdgesMenu.setEnabled(displayEdgesCheckBoxMenuItem.isSelected());
        updateVisibility();
    }//GEN-LAST:event_displayEdgesCheckBoxMenuItemActionPerformed

    private void showListDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListDialogActionPerformed
        ListDialog.showDialog(this);
    }//GEN-LAST:event_showListDialogActionPerformed

    /**
     * Returns true if the node is shown, false otherwise
     * @param node Node
     * @return True if the node is shown, false otherwise
     */
    private boolean isNodeShown(org.graphstream.graph.Node node) {
        boolean shown = true;
        switch (node.toString().charAt(0)) {
            case 'V':
                if (!displayCitiesCheckBoxMenuItem.isSelected()) shown = false;
                break;
            case 'R':
                if (!displayRestaurantsCheckBoxMenuItem.isSelected()) shown = false;
                break;
            case 'L':
                if (!displayLeisuresCheckBoxMenuItem.isSelected()) shown = false;
                break;
            default:
                break;
        }
        return shown;
    }
    
    /**
     * Returns true if the edge is shown, false otherwise
     * @param edge Edge
     * @return True if the edge is shown, false otherwise
     */
    private boolean isEdgeShown(org.graphstream.graph.Edge edge) {
        boolean shown = true;
        if (!isNodeShown(edge.getNode0()) || !isNodeShown(edge.getNode1()) || !displayEdgesCheckBoxMenuItem.isSelected()) {
            shown = false;
        } else switch (edge.toString().charAt(0)) {
            case 'N':
                if (!displayNationalRoadsCheckBoxMenuItem.isSelected()) shown = false;
                break;
            case 'D':
                if (!displayDepartementalRoadsCheckBoxMenuItem.isSelected()) shown = false;
                break;
            case 'A':
                if (!displayHighwaysCheckBoxMenuItem.isSelected()) shown = false;
                break;
            default:
                break;
        }
        return shown;
    }
    
    /**
     * Updates visilibility
     */
    private void updateVisibility() {
        for (int i = 0; i < graph.getNodeCount(); i++) {
            org.graphstream.graph.Node node = graph.getNode(i);
            if (isNodeShown(node)) {
                node.removeAttribute("ui.hide");
            } else {
                node.setAttribute("ui.hide");
            }
        }
        for (int i = 0; i < graph.getEdgeCount(); i++) {
            org.graphstream.graph.Edge edge = graph.getEdge(i);
            if (isEdgeShown(edge)) {
                edge.removeAttribute("ui.hide");
            } else {
                edge.setAttribute("ui.hide");
            }
        }
    }
    
    /**
     * Represents the city combo List Model
     */
    private class CityComboBoxModel extends DefaultComboBoxModel {
        
        // List of all the nodes that are cities
        private final List<Node> nodes;
        
        /**
         * Instanciates a new model
         * @param nodes List of all the nodes that are cities
         */
        public CityComboBoxModel(List<Node> nodes) {
            this.nodes = nodes;
        }
        
        /**
         * Returns the number of nodes that are cities
         * @return Number of nodes that are cities
         */
        @Override
        public int getSize() {
            return nodes.size();
        }
        
        /**
         * Returns the name of the city at a given index
         * @param index Index of the city
         * @return Name of the city at the given index
         */
        @Override
        public String getElementAt(int index) {
            return this.nodes.get(index).getName();
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton compareButton;
    private javax.swing.JPanel comparePanel;
    private javax.swing.JCheckBoxMenuItem displayCitiesCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem displayDepartementalRoadsCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem displayDistancesCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem displayEdgesCheckBoxMenuItem;
    private javax.swing.JMenu displayEdgesMenu;
    private javax.swing.JCheckBoxMenuItem displayHighwaysCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem displayLeisuresCheckBoxMenuItem;
    private javax.swing.JMenu displayMenu;
    private javax.swing.JCheckBoxMenuItem displayNationalRoadsCheckBoxMenuItem;
    private javax.swing.JMenu displayNodesMenu;
    private javax.swing.JCheckBoxMenuItem displayNodesTitlesCheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem displayRestaurantsCheckBoxMenuItem;
    private javax.swing.JPanel distanceOptionsPanel;
    private javax.swing.JPanel distancePanel;
    private javax.swing.JLabel edgesInformationsLabel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox<String> firstCityComboBox;
    private javax.swing.JLabel firstCityLabel;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel maxDistanceLabel;
    private javax.swing.JSpinner maxDistanceSpinner;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nodeTitle;
    private javax.swing.JLabel nodesInformationsLabel;
    private javax.swing.JMenuItem openFileMenuItem;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JComboBox<String> secondCityComboBox;
    private javax.swing.JLabel secondCityLabel;
    private javax.swing.JPopupMenu.Separator separator1;
    private javax.swing.JMenuItem showListDialog;
    private javax.swing.JButton visualizeButton;
    // End of variables declaration//GEN-END:variables
}
